ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks'))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('contact', views.contact, name='contact'),
    path('create_list', views.create_list, name='create_list'),
    path('active_lists', views.active_lists, name='active_lists'),
    path('archived_lists', views.archived_lists, name='archived_lists'),
    path('list/<int:list_id>', views.list_page, name='list_page'),
    path('change_background', views.change_background, name='change_background')
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class User(AbstractUser):
    background = models.CharField(default='linear-gradient(to top, #48c6ef 0%, #6f86d6 100%)', max_length=300)

class ToDoList(models.Model):
    author = models.ForeignKey("User", on_delete=models.CASCADE, related_name='to_do_lists')
    name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

class Task(models.Model):
    task_name = models.CharField(max_length=100)
    to_do_list = models.ForeignKey("ToDoList", on_delete=models.CASCADE, related_name='tasks')
    importance = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    time_start = models.TimeField(blank=True)
    time_end = models.TimeField(blank=True)
    done = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.task_name}'

tasks/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.template.defaulttags import register

# Create your views here.
from .models import User, ToDoList, Task

def index(request):
    return render(request, 'tasks/index.html')

@register.filter
def get_range(value):
    return range(value)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request, 'tasks/login.html', {
                'error_message':'Invalid credentials.'
            })
    else:
        return render(request, 'tasks/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('tasks:index'))

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']

        password = request.POST['password']
        confirm_password = request.POST['confirm-password']
        
        if password != confirm_password:
            return render(request, 'tasks/register.html', {'error_message':'Password must match.'})

        new_user = User.objects.create_user(username,email,password)
        new_user.save()
        login(request, new_user)
        return render(request, 'tasks/index.html', {'success_message':'Registration successful!'})
        
    return render(request, 'tasks/register.html')

def contact(request):
    return render(request, 'tasks/contact.html')

@login_required
def active_lists(request):
    user = request.user
    active_lists = user.to_do_lists.filter(archived=False).all()
    return render(request, 'tasks/active_lists.html', {'active_lists':active_lists})

@login_required
def archived_lists(request):
    user = request.user
    archived_lists = user.to_do_lists.filter(archived=True).all()
    return render(request, 'tasks/archived_lists.html', {'archived_lists':archived_lists})

@login_required
def create_list(request):
    if request.method == 'POST':
        list_name = request.POST['list-name']
        try:
            new_list = ToDoList.objects.create(author=request.user, name=list_name)
            new_list.save()
            messages.success(request, 'List created!')
            return HttpResponseRedirect(reverse('tasks:active_lists'))
        except:
            context = {
                'error_message':f'There was an issue creating your List {list_name}'
            }
            return render(request, 'tasks/create_list.html', context)

    return render(request, 'tasks/create_list.html')

@login_required
def list_page(request, list_id):
    if request.method == 'POST':
        if 'done-task' in request.POST:
            task_id = request.POST['task-done']
            try:
                task = Task.objects.get(pk=int(task_id))
                task.done = True
                task.save()

                current_list = ToDoList.objects.get(pk=list_id)
                context = {
                    'success_message':f'Task done {task}!',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
                }
                return render(request, 'tasks/list_page.html', context)
            except:
                current_list = ToDoList.objects.get(pk=list_id)
                context = {
                    'error_message':f'There was an issue, {task_name}',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
                }
                return render(request, 'tasks/list_page.html', context)

        if 'delete-task' in request.POST:
            task_id = request.POST['task-delete']
            try:
                Task.objects.get(pk=int(task_id)).delete()

                current_list = ToDoList.objects.get(pk=list_id)
                context = {
                    'success_message':f'Task deleted!',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
                }
                return render(request, 'tasks/list_page.html', context)
            except:
                current_list = ToDoList.objects.get(pk=list_id)
                context = {
                    'error_message':f'There was an issue, {task_name}',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
                }
                return render(request, 'tasks/list_page.html', context)

        if 'restart' in request.POST:
            to_do_list = ToDoList.objects.get(pk=list_id)

            for task in to_do_list.tasks.all():
                task.done = False
                task.save()


            current_list = ToDoList.objects.get(pk=list_id)
            context = {
                    'success_message':f'List status changed!',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
            }
            return render(request, 'tasks/list_page.html', context)
            

        if 'archive-list' in request.POST:
            to_do_list = ToDoList.objects.get(pk=list_id)
            if to_do_list.archived == True:
                to_do_list.archived = False

                for task in to_do_list.tasks.all():
                    task.done = False
                    task.save()
            else:
                to_do_list.archived = True
            to_do_list.save()

            user = request.user
            active_lists = user.to_do_lists.filter(archived=False).all()
            context = {
                    'success_message':f'List status changed!',
                    'active_lists':active_lists
            }
            return render(request, 'tasks/active_lists.html', context)
            
        if 'add-task' in request.POST:
            task_name = request.POST['task-name']
            to_do_list = ToDoList.objects.get(pk=list_id)
            importance = request.POST['importance']
            time_start = request.POST['time-start']
            time_end = request.POST['time-end']
            try:
                new_task = Task.objects.create(
                    task_name=task_name,
                    to_do_list=to_do_list,
                    importance=importance,
                    time_start=time_start,
                    time_end=time_end
                )
                new_task.save()
                messages.success(request, 'Task saved!')
                return HttpResponseRedirect(reverse("task:list_page",args=[to_do_list.id]))
            except:
                current_list = ToDoList.objects.get(pk=list_id)
                context = {
                    'error_message':'There was an issue creating your Task',
                    'list': current_list,
                    'tasks':current_list.tasks.all()
                }
                return render(request, 'tasks/list_page.html', context)
        
    
    
    current_list = ToDoList.objects.get(pk=list_id)
    tasks = current_list.tasks.order_by('time_start')
    context = {
        'list': current_list,
        'tasks':tasks
    }
    return render(request, 'tasks/list_page.html', context)

def change_background(request):
    if request.method == 'POST':
        user = request.user
        color = request.POST['color']
        user.background = color
        user.save()
        return render(request, 'tasks/change_background.html', {"message": 'Background changed!'})
    return render(request, 'tasks/change_background.html')

tasks/templates/tasks/active_lists.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<section class='container'>
    <div class='row'>
        {% for list in active_lists %}
            <div class='col-md-4 my-5 text-center'>
            <a href = "{% url 'tasks:list_page' list.id %}">
                <div class='with-shadow mx-4 p-5'>
                <img src="{% static 'tasks/logo.png' %}" style='width:100px;height:100px'>
                <h4 class='font-weight-bold'>{{ list.name }}</h4>
                <p>Created on: <span>{{ list.date_created }}</span></p>
                </div>
            </a>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

tasks/templates/tasks/archived_lists.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<section class='container'>
    <div class='row'>
        {% for list in archived_lists %}
            <div class='col-md-4 my-5 text-center'>
            <a href = "{% url 'tasks:list_page' list.id %}">
                <div class='with-shadow mx-4 p-5'>
                <h4 class='font-weight-bold'>{{ list.name }}</h4>
                <p>Created on: <span>{{ list.date_created }}</span></p>
                </div>
            </a>
            </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

tasks/templates/tasks/change_background.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<section class='container'>
    <div class='row'>
        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%);width:250px;height:250px" value=''>
            </form>
        </div>
        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to right, #434343 0%, black 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to right, #434343 0%, black 100%);width:250px;height:250px" value=''>
            </form>
        </div>
        
        <div class='col-md-3 my-3 text-center'>
                    <form action="{% url 'tasks:change_background' %}" method=POST>
                        {% csrf_token %}
                        <input type='hidden' name='color' value="linear-gradient(to top, #a18cd1 0%, #fbc2eb 100%);">
                        <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #a18cd1 0%, #fbc2eb 100%);width:250px;height:250px" value=''>
                    </form>
        </div>

        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%);width:250px;height:250px" value=''>
            </form>
        </div>

        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(120deg, #f093fb 0%, #f5576c 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(120deg, #f093fb 0%, #f5576c 100%);width:250px;height:250px" value=''>
            </form>
        </div>

        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #30cfd0 0%, #330867 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #30cfd0 0%, #330867 100%);width:250px;height:250px" value=''>
            </form>
        </div>

        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #0ba360 0%, #3cba92 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #0ba360 0%, #3cba92 100%);width:250px;height:250px" value=''>
            </form>
        </div>

        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #ff0844 0%, #ffb199 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #ff0844 0%, #ffb199 100%);width:250px;height:250px" value=''>
            </form>
        </div>

        <!--  -->


        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #cd9cf2 0%, #f6f3ff 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #cd9cf2 0%, #f6f3ff 100%);width:250px;height:250px" value=''>
            </form>
        </div>
        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #37ecba 0%, #72afd3 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #37ecba 0%, #72afd3 100%);width:250px;height:250px" value=''>
            </form>
        </div>
        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(to top, #6a85b6 0%, #bac8e0 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(to top, #6a85b6 0%, #bac8e0 100%);width:250px;height:250px" value=''>
            </form>
        </div>
        <div class='col-md-3 my-3 text-center'>
            <form action="{% url 'tasks:change_background' %}" method=POST>
                {% csrf_token %}
                <input type='hidden' name='color' value="linear-gradient(-20deg, #ddd6f3 0%, #faaca8 100%, #faaca8 100%);">
                <input type='submit' name='bg-color' class='border-dark rounded-circle' style="background-image: linear-gradient(-20deg, #ddd6f3 0%, #faaca8 100%, #faaca8 100%);width:250px;height:250px" value=''>
            </form>
        </div>
    </div>
</section>
{% endblock %}

tasks/templates/tasks/contact.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<div class='row justify-content-center'>
    <img src="{% static 'tasks/logo.png' %}" style='width:200px;height:200px'>
</div>
<div class='row justify-content-center'>
    <div class='with-bg col-md-4 p-4 text-center form-group'>
        <h1 class='my-4 display-4 font-weight-bold'>Created by</h1>
        <p>Milena Kowalska</p>
        <p><a href="#">kow.milena@gmail.com</a></p>

    </div>
</div>
{% endblock %}

tasks/templates/tasks/create_list.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<div class='row justify-content-center'>
    <img src="{% static 'tasks/logo.png' %}" style='width:200px;height:200px'>
</div>
<div class='row justify-content-center'>
    <div class='with-bg col-md-4 p-4 text-center form-group'>
        <h1 class='my-4 display-4 font-weight-bold'>New ToDo-List</h1>
        <form action="{% url 'tasks:create_list' %}" method="POST">
            {% csrf_token %}
            <input class='mt-2 mb-2 form-control form-control-lg' type="text" name='list-name' placeholder="List Name"><br>
            <input class='mt-2 mb-4 btn btn-primary btn-lg btn-block' type="submit" value='Save'><br>
        </form>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<div class='justify-content-center'>
    <div class='text-center form-group'>
    <img id='logo' src="{% static 'tasks/logo.png' %}">
    </div>
    <div class='row justify-content-center text-center'>
        {% if user.is_authenticated %}
        <div class='col-md-3'>
            <a href="{% url 'tasks:logout' %}"><button class='btn btn-dark btn-lg' style='font-size:50px;height:120px;width:300px'>Log out</button></a>
        </div>
        {% else %}
        <div class='col-md-3'>
            <a href="{% url 'tasks:login' %}"><button class='btn btn-dark btn-lg' style='font-size:50px;height:120px;width:300px'>Sign in</button></a>
        </div>
        <div class='col-md-3'>
            <a href="{% url 'tasks:register' %}"><button class='btn btn-dark btn-lg' style='font-size:50px;height:120px;width:300px'>Get started</button></a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>ToDoList - {{ title }}</title>
    {% else %}
    <title>ToDoList</title>
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/a13e52ee0b.js" crossorigin="anonymous"></script>
    {% if user.is_authenticated %}
    <style>

    </style>
    {% else %}
    <style>
    body {
        background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
    }</style>
    {% endif %}

    <style>
        body {
            height: 100vh;
            max-width: 100%
        }


        .with-bg, .with-shadow {
            background-color: #DCD9D4;
            background-image: linear-gradient(to bottom, rgba(255,255,255,0.50) 0%, rgba(0,0,0,0.50) 100%), radial-gradient(at 50% 0%, rgba(255,255,255,0.10) 0%, rgba(0,0,0,0.50) 50%);
            background-blend-mode: soft-light,screen;
            color: black;
            border-radius: 15px;    
            }

        .with-shadow:hover, .rounded-circle:hover{
            box-shadow: 0 20px 20px 0 rgba(0, 0, 0, 0.2), 0 20px 20px 0 rgba(0, 0, 0, 0.19);
        }
        i.icon-button {
            color:rgb(122, 122, 122);
            font-size: 20px;
        }
        i.icon-button:hover {
            color:white;
        }
        
        footer {
            position: fixed;
            background-color: rgb(51, 57, 61);
            bottom: 0;
            color: rgb(172, 172, 172);
        }

        #logo {
            width:800px;
            height:800px;
        }
        .maindiv {
            width: 100%;
        }
        input[type=radio] {
            width: 30px;
            height: 30px;
        }

        @media only screen and (max-width: 800px){
            #logo {
                width: 100%;
                height: auto;
            }
            .maindiv {
                width: 90%;
                margin: auto;
                margin-bottom: 100px;
            }
            body {
                height: 100%;
                min-height: 100vh;
            }

            footer {
                margin-top: 10px;
            }
            h1 {
                font-size: 30px;
            }
            h2 {
                font-size:25px;
            }
            .col-md-1 {
                width: 50%;
                padding: 0;
            }
            h4 {
                text-align: center;
                font-size: 20px;
            }
            .with-bg {
                padding: 10px 20px !important;

            }
            .hours {
                font-size: 10px;
            }
            input[type=radio] {
            width: 15px;
            height: 15px; 
            margin: 0
            }
            .form-check-label {
                font-size: 15px;
            }
            #importance {
                width:100% !important;
                flex: 100%;
                max-width: 100%;
            }

            label[for=importance]{
                display: none;
            }
            label[for=time-start], label[for=time-end]{
                font-size: 10px;
            }
        }

            
        }



        .task {
            border-radius: 10px;
            color:rgb(172, 172, 172)
        }
    </style>
</head>
<body style='{% if user.is_authenticated %}background-image:{{ user.background }}{% else %}background-image:linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);{% endif %}'>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'tasks:index' %}"><i class="fas fa-house-user"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:active_lists' %}">Active Lists</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:create_list' %}">Create new List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:archived_lists' %}">Archived Lists</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:change_background' %}">Change background</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:logout' %}">Log out</a>
            </li>
            {% else %}
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:login' %}">Sign in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:register' %}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:contact' %}">Contact us</a>
            </li>
          </ul>
        </div>
      </nav>

      {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">{{ message }}</div>
            {% endfor %}
      {% elif success_message %}
            <div class="alert alert-success">{{ success_message }}</div>
      {% elif error_message %}
        <div class="alert alert-danger">{{ error_message }}</div>
      {% endif %}

    <div class='maindiv'>
    {% block body %}
    {% endblock %}
    </div>
    
    <footer class='text-center mt-5 w-100 pt-3'>
        <p>Designed and developed by Milena Kowalska</p>
    </footer>
</body>
</html>

tasks/templates/tasks/login.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<div class='row justify-content-center'>
    <img src="{% static 'tasks/logo.png' %}" style='width:200px;height:200px'>
</div>
<div class='row justify-content-center'>
    <div class='with-bg col-md-4 p-4 text-center form-group'>
        <h1 class='my-4 display-4 font-weight-bold'>Login</h1>
        <form action="{% url 'tasks:login' %}" method="POST">
            {% csrf_token %}
            <input class='mt-2 mb-2 form-control form-control-lg' type="text" name='username' placeholder="Username"><br>
            <input class='mt-2 mb-2 form-control form-control-lg' type="password" name='password' placeholder="Password"><br>
            <input class='mt-2 mb-4 btn btn-primary btn-lg btn-block' type="submit" value='Sign in'><br>
        </form>
        <p>Need an Account? <a href="{% url 'tasks:register' %}">Register now</a></p>

    </div>
</div>
{% endblock %}

tasks/templates/tasks/register.html
{% extends 'tasks/layout.html' %}
{% load static %}

{% block body %}
<div class='row justify-content-center'>
    <img src="{% static 'tasks/logo.png' %}" style='width:200px;height:200px'>
</div>
<div class='row justify-content-center'>
    <div class='with-bg col-md-4 p-4 text-center form-group'>
        <h1 class='my-4 display-4 font-weight-bold'>Register</h1>
        <form action="{% url 'tasks:register' %}" method="POST">
            {% csrf_token %}
            <input class='mt-2 mb-2 form-control form-control-lg' type="text" name='username' placeholder="Username"><br>
            <input class='mt-2 mb-2 form-control form-control-lg' type="text" name='email' placeholder="Email"><br>
            <input class='mt-2 mb-2 form-control form-control-lg' type="password" name='password' placeholder="Password"><br>
            <input class='mt-2 mb-2 form-control form-control-lg' type="password" name='confirm-password' placeholder="Confirm password"><br>
            <input class='mt-2 mb-4 btn btn-primary btn-lg btn-block' type="submit" value='Submit'><br>
        </form>
        <p>Already have an Account? <a href="{% url 'tasks:login' %}">Sign in</a></p>
    </div>
</div>
{% endblock %}